platform :ios, "12.0"
plugin "cocoapods-xcframework"

use_frameworks! :linkage => :static

target "demo" do
  pod "Alamofire", binary: true
  pod "SwiftDate", binary: true
end

target "ModuleA" do
  platform :ios, "12.0"
  pod "MondrianLayout", binary: true
  pod "Brightroom"  
end

target "ModuleB" do
  platform :ios, "12.0"
  pod "Reusable"
end
