name: Tests

on: [push]

jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "13"
      - uses: actions/checkout@v1
      - name: Test
        run: |
          bundle install
          cd demo-xcframework
          bundle exec pod deintegrate
          bundle exec pod install
