name: Tests

on: [push]

jobs:
  build:
    runs-on: macos-11
    steps:
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            cocoapods
            bundler
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "13"
      - uses: actions/checkout@v1
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Test
        run: |
          gem install bundler          
          bundle install
          cd demo-xcframework
          bundle exec pod deintegrate
          bundle exec pod install
